global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "linux-node-exporters"
    static_configs:
      - targets:
          - "192.168.30.11:9100"
          - "192.168.30.12:9100"
          - "192.168.30.13:9100"

  - job_name: "synology-exporter"
    static_configs:
      - targets:
          - "192.168.30.4:9100"

  - job_name: "fritzbox"
    static_configs:
      - targets:
          - "192.168.30.11:9787"

  - job_name: "betterfritzbox"
    static_configs:
      - targets:
          - "192.168.30.11:9042"

  - job_name: 'pve'
    static_configs:
      - targets:
        - 192.168.30.5  # Proxmox VE node 1
        - 192.168.30.6  # Proxmox VE node 2
        - 192.168.30.7  # Proxmox VE node 3
    metrics_path: /pve
    params:
      module: [default]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 192.168.30.11:9221

  - job_name: 'cadvisor'
    static_configs:
      - targets: 
        - '192.168.30.11:8089'
        - '192.168.30.12:8089'
        - '192.168.30.13:8089'