global:
  scrape_interval: 15s  # Wie oft Prometheus Daten sammelt
  evaluation_interval: 15s  # Wie oft Regeln ausgewertet werden

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]