global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "linux-node-exporters"
    static_configs:
      - targets:
          - "192.168.30.11:9100"
          - "192.168.30.12:9100"
          - "192.168.30.13:9100"
