services:
  fritzbox-exporter:
    image: ghcr.io/sberk42/fritzbox_exporter/fritzbox_exporter:latest
    environment:
      USERNAME: ${USERNAME}
      PASSWORD: ${PASSWORD}
      GATEWAY_URL: ${GATEWAY_URL}
    restart: unless-stopped
    ports:
      - "8080:8080"