// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1730040933);
user_pref("app.update.lastUpdateTime.region-update-timer", 1730040933);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1730040933);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1730040933);
user_pref("browser.policies.applied", true);
user_pref("browser.region.update.updated", 1730040906);
user_pref("browser.search.region", "DE");
user_pref("calendar.caldav.googleResync", 1730040903);
user_pref("calendar.list.sortOrder", "3bcb62e4-bad8-45b6-9326-50aa6a31f1b4");
user_pref("calendar.registry.3bcb62e4-bad8-45b6-9326-50aa6a31f1b4.calendar-main-default", true);
user_pref("calendar.registry.3bcb62e4-bad8-45b6-9326-50aa6a31f1b4.calendar-main-in-composite", true);
user_pref("calendar.registry.3bcb62e4-bad8-45b6-9326-50aa6a31f1b4.disabled", true);
user_pref("calendar.registry.3bcb62e4-bad8-45b6-9326-50aa6a31f1b4.name", "Home");
user_pref("calendar.registry.3bcb62e4-bad8-45b6-9326-50aa6a31f1b4.type", "storage");
user_pref("calendar.registry.3bcb62e4-bad8-45b6-9326-50aa6a31f1b4.uri", "moz-storage-calendar://");
user_pref("calendar.timezone.local", "UTC");
user_pref("calendar.timezone.useSystemTimezone", true);
user_pref("calendar.ui.version", 3);
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 36);
user_pref("extensions.getAddons.cache.lastUpdate", 1730040933);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.lastAppBuildId", "20240923211920");
user_pref("extensions.lastAppVersion", "128.2.2");
user_pref("extensions.lastPlatformVersion", "128.2.0");
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webextensions.uuids", "{\"default-theme@mozilla.org\":\"aa887c66-5bb7-4a4d-8099-1700ac8f76d2\",\"juraj.masiar@gmail.com_LinkInTab\":\"f312cb6c-b6b1-45a9-bd2c-9f14e012d9fa\"}");
user_pref("gecko.handlerService.defaultHandlersVersion", 1);
user_pref("mail.rights.version", 1);
user_pref("mail.ui-rdf.version", 43);
user_pref("mailnews.database.global.datastore.id", "d72d7c09-3d88-4cea-ab66-47881930d1e");
user_pref("mailnews.headers.extraAddonHeaders", "autocrypt openpgp");
user_pref("mailnews.quotingPrefs.version", 1);
user_pref("mailnews.start_page_override.mstone", "128.2.2");
user_pref("mailnews.tags.$label1.color", "#FF0000");
user_pref("mailnews.tags.$label1.tag", "Important");
user_pref("mailnews.tags.$label2.color", "#FF9900");
user_pref("mailnews.tags.$label2.tag", "Work");
user_pref("mailnews.tags.$label3.color", "#009900");
user_pref("mailnews.tags.$label3.tag", "Personal");
user_pref("mailnews.tags.$label4.color", "#3333FF");
user_pref("mailnews.tags.$label4.tag", "To Do");
user_pref("mailnews.tags.$label5.color", "#993399");
user_pref("mailnews.tags.$label5.tag", "Later");
user_pref("mailnews.tags.version", 2);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("services.settings.clock_skew_seconds", -10900);
user_pref("services.settings.last_etag", "\"1648185887941\"");
user_pref("services.settings.last_update_seconds", 1730051833);
user_pref("services.settings.thunderbird.hijack-blocklists.last_check", 1730051833);
user_pref("services.settings.thunderbird.search-config.last_check", 1730051833);
user_pref("services.settings.thunderbird.url-classifier-skip-urls.last_check", 1730051833);
user_pref("toolkit.telemetry.cachedClientID", "b6d4c659-2fc6-4632-a855-14f2c3c5b0f8");
user_pref("toolkit.telemetry.previousBuildID", "20240923211920");
