---
- name: Ensure the system is up to date
  apt:
    update_cache: yes
    upgrade: dist
    autoremove: yes
    autoclean: yes

- name: Install unattended-upgrades
  apt:
    name: unattended-upgrades
    state: present

- name: Enable automatic updates
  lineinfile:
    path: /etc/apt/apt.conf.d/20auto-upgrades
    regexp: '^//?APT::Periodic::Unattended-Upgrade'
    line: 'APT::Periodic::Unattended-Upgrade "1";'
    state: present
