version: "3.4"
services:
  broker:
    image: docker.io/library/redis:7
    restart: unless-stopped
    volumes:
      - redisdata:/data

  db:
    image: docker.io/library/postgres:15
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: paperless
      POSTGRES_USER: paperless
      POSTGRES_PASSWORD: paperless

  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    restart: unless-stopped
    depends_on:
      - db
      - broker
      - gotenberg
      - tika
    ports:
      - "8000:8000"
    volumes:
      - /mnt/nfs/paperless-data:/usr/src/paperless/data
      - /mnt/nfs/paperless-media:/usr/src/paperless/media
      - /mnt/nfs/paperless-export:/usr/src/paperless/export
      - /mnt/nfs/paperless-consume:/usr/src/paperless/consume
    environment:
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_DBHOST: db
      PAPERLESS_TIKA_ENABLED: 1
      PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://gotenberg:3000
      PAPERLESS_TIKA_ENDPOINT: http://tika:9998
      PAPERLESS_OCR_LANGUAGES: de
      USERMAP_UID: 1000
      USERMAP_GID: 1000
      POSTGRES_DB:
      POSTGRES_USER:
      POSTGRES_PASSWORD:
      PAPERLESS_SECRET_KEY:
      PAPERLESS_TIME_ZONE:
      PAPERLESS_OCR_LANGUAGE:
      PAPERLESS_ADMIN_USER:
      PAPERLESS_ADMIN_PASSWORD:
      PAPERLESS_URL:
      PAPERLESS_CONSUMER_POLLING: 10
      PAPERLESS_CONSUMER_ENABLE_BARCODES: 1
      PAPERLESS_CONSUMER_ENABLE_ASN_BARCODE: 1



  gotenberg:
    image: docker.io/gotenberg/gotenberg:8
    restart: unless-stopped
    command:
      - "gotenberg"
      - "--chromium-disable-javascript=true"
      - "--chromium-allow-list=file:///tmp/.*"

  tika:
    image: ghcr.io/paperless-ngx/tika:latest
    restart: unless-stopped

volumes:
  data:
  media:
  pgdata:
  redisdata: