services:
  broker:
    image: docker.io/library/redis:7
    restart: always
    volumes:
      - redisdata:/data

  db:
    image: docker.io/library/postgres:16
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data


  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:2.12.1
    restart: always
    depends_on:
      - db
      - broker
    ports:
      - "8010:8000"
    volumes:
      - data:/usr/src/paperless/data
      - media:/usr/src/paperless/media
      - /mnt/nfs/paperless-export:/usr/src/paperless/export
      - /mnt/nfs/paperless-consume:/usr/src/paperless/consume
volumes:
  data:
  media:
  pgdata:
  redisdata: