services:
  broker:
    image: redis:6.0
    restart: unless-stopped

  db:
    image: postgres:13
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/data


  webserver:
    image: jonaswinkler/paperless-ng:latest
    restart: always
    depends_on:
      - db
      - broker
    ports:
      - "8010:8000"
    volumes:
      - data:/usr/src/paperless/data
      - media:/usr/src/paperless/media
      - /mnt/nfs/paperless-export:/usr/src/paperless/export
      - /mnt/nfs/paperless-consume:/usr/src/paperless/consume
volumes:
  data:
  media:
  pgdata:
  redisdata: