---
- name: Install UFW
  apt:
    name: ufw
    state: present

- name: Allow specified ports through the firewall
  ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
  loop: "{{ allowed_ports }}"

- name: Enable UFW
  ufw:
    state: enabled
    default: deny
    logging: on
