- name: Install NFS client packages for Debian
  apt:
    name: nfs-common
    state: present
  when: ansible_os_family == "Debian"

- name: Install NFS client packages for RedHat/CentOS
  yum:
    name: nfs-utils
    state: present
  when: ansible_os_family == "RedHat"

- name: Create mount directories
  file:
    path: "{{ item.mount_point }}"
    state: directory
    mode: '0777'
  loop: "{{ nfs_mounts }}"

- name: Mount NFS shares
  mount:
    path: "{{ item.mount_point }}"
    src: "{{ item.nfs_server }}:{{ item.nfs_share }}"
    fstype: nfs
    opts: rw,noatime
    state: mounted
  loop: "{{ nfs_mounts }}"

- name: Ensure NFS mounts are persistent in /etc/fstab
  mount:
    path: "{{ item.mount_point }}"
    src: "{{ item.nfs_server }}:{{ item.nfs_share }}"
    fstype: nfs
    opts: rw,noatime
    state: present
  loop: "{{ nfs_mounts }}"

# - name: Set ownership for philip on NFS mount points
#   file:
#     path: "{{ item.mount_point }}"
#     owner: 1000  # UID von philip
#     group: 1000  # GID von philip
#     mode: '0777'
#   loop: "{{ nfs_mounts }}"
#   when: ansible_user == "philip"