---
- name: Install NFS client packages
  apt:
    name: nfs-common
    state: present
  when: ansible_os_family == "Debian"

- name: Install NFS client packages for RedHat/CentOS
  yum:
    name: nfs-utils
    state: present
  when: ansible_os_family == "RedHat"

- name: Create the mount directory
  file:
    path: "{{ mount_point }}"
    state: directory
    mode: '0777'

- name: Mount NFS share
  mount:
    path: "{{ mount_point }}"
    src: "{{ nfs_server }}:{{ nfs_share }}"
    fstype: nfs
    opts: defaults
    state: mounted

- name: Ensure NFS mount is persistent in /etc/fstab
  mount:
    path: "{{ mount_point }}"
    src: "{{ nfs_server }}:{{ nfs_share }}"
    fstype: nfs
    opts: defaults
    state: present
