# review .env at https://github.com/danny-avila/LibreChat/blob/main/.env.example
services:
  api:
    image: librechat/librechat-dev:latest
    container_name: LibreChat
    ports:
      - 3080:3080
    restart: always
    env_file:
      - stack.env
    environment:
      - HOST=0.0.0.0
      - NODE_ENV=production
      - MONGO_URI=mongodb://mongodb:27017/LibreChat
      - MEILI_HOST=http://meilisearch:7700
   # https://hub.docker.com/u/librechat - uses single image from DockerFile 
    volumes:
      - /LibreChat/images:/app/client/public/images
  meilisearch:
    container_name: chat-meilisearch
    image: getmeili/meilisearch:v1.5.1
    restart: always
    env_file:
      - stack.env
    environment:
      - MEILI_HOST=http://meilisearch:7700
      - MEILI_NO_ANALYTICS=true
    volumes:
      - /LibreChat/meili_data_v1.5:/meili_data
  mongodb:
    container_name: chat-mongodb
    # ports:  # Uncomment this to access mongodb from outside docker, not safe in deployment
    #   - 27018:27017
    # Modify to mongo:4.4.18 for missing AVX CPU
    image: mongo:4.4.18
    restart: always
    volumes:
      - /LibreChat/data-node:/data/db
    command: mongod --noauth