---
- name: Ensure users exist
  user:
    name: "{{ item.name }}"
    shell: "{{ item.shell }}"
    state: present
  loop: "{{ users }}"

- name: Add SSH keys for users
  authorized_key:
    user: "{{ item.name }}"
    state: present
    key: "{{ lookup('file', item.ssh_key) }}"
  loop: "{{ users }}"

- name: Harden SSH configuration
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?PermitRootLogin'
    line: 'PermitRootLogin no'
    state: present

- name: Restart SSH
  service:
    name: ssh
    state: restarted
