- name: Install common packages
  apt:
    name: "{{ item }}"
    state: present
  loop: "{{ packages }}"
- name: Ensure qemu-guest-agent is installed
  ansible.builtin.package:
    name: qemu-guest-agent
    state: present

- name: Ensure qemu-guest-agent is enabled and started
  ansible.builtin.service:
    name: qemu-guest-agent
    state: started
    enabled: true