services:
  mariadb:
      image: mariadb:11.5.2
      volumes:
      - database:/var/lib/mysql

  wordpress:
      image: wordpress:6.6.2
      depends_on:
          - mariadb
      ports:
          - 8080:80
      restart: always
      volumes:
          - wordpress:/var/www/html
volumes:
    wordpress:
    database: