# documentation: https://github.com/jlesage/docker-thunderbird
services:
  thunderbird:
    image: jlesage/thunderbird
    container_name: thunderbird
    environment:
      USER_ID: 1000
      GROUP_ID: 1000
    volumes:
      # Beispiel-Mounts
      - /mnt/mailstore:/config
    ports:
      # Beispiel-Port-Weiterleitung
      - 5800:5800
      - 5900:5900
    restart: unless-stopped