services:
  thunderbird:
    image: jlesage/thunderbird
    container_name: thunderbird
    volumes:
      # Beispiel-Mounts
      - ./thunderbird2:/thunderbird
    ports:
      # Beispiel-Port-Weiterleitung
      - 5800:5800
      - 5900:5900
    restart: unless-stopped
