# documentation: https://github.com/jlesage/docker-thunderbird
services:
  thunderbird:
    image: jlesage/thunderbird
    container_name: thunderbird
    volumes:
      # Beispiel-Mounts
      - /mnt/mailstore/thunderbird:/
    ports:
      # Beispiel-Port-Weiterleitung
      - 5800:5800
      - 5900:5900
    restart: unless-stopped
