services:
  server:
    image: hugomods/hugo:latest
    container_name: hugo
    restart: always
    command: hugo server --watch --bind 0.0.0.0
    ports:
      - "1313:1313"
    volumes:
      - "philipblog:/src"