services:
  fritz-exporter:
    image: pdreker/fritz_exporter:2
    container_name: fritz-exporter
    restart: unless-stopped
    environment:
      FRITZ_HOSTNAME: ${FRITZ_HOSTNAME}
      FRITZ_USERNAME: ${FRITZ_USERNAME}
      FRITZ_PASSWORD: ${FRITZ_PASSWORD}
    ports:
      - "9787:9787"