all:
  hosts:
    boba-fett:
      ansible_host: 192.168.30.11
      ansible_user: philip
      ansible_ssh_private_key_file: ~/.ssh/id_rsa
    obi-wan:
      ansible_host: 192.168.30.12
      ansible_user: philip
      ansible_ssh_private_key_file: ~/.ssh/id_rsa
    darth-vader:
      ansible_host: 192.168.30.13
      ansible_user: philip
      ansible_ssh_private_key_file: ~/.ssh/id_rsa
    debian-test:
      ansible_host: 192.168.30.99
      ansible_user: philip
      ansible_ssh_private_key_file: ~/.ssh/id_rsa
observer:
  hosts:
    boba-fett: