- hosts: all
  become: true
  roles:
    - ftp_user
    - firewall
    - packages
    - portainer_agent
    - users
    - update
    - time
    - nfsmount
- hosts: observer
  become: true
  roles:
    - portainer