- hosts: localruns
  become: true
  roles:
    - pwshin3days
- hosts: all
  become: true
  roles:
    - packages
    - nfsmount
    - firewall
    - portainer_agent
    - users
    - update
    - time
- hosts: observer
  become: true
  roles:
    - portainer
