- hosts: all
  become: true
  roles:
    - geerlingguy.node_exporter
    - packages
    - nfsmount
    - firewall
    - portainer_agent
    - users
    - update
    - time
- hosts: observer
  become: true
  roles:
    - portainer
